# frontend/Dockerfile.prod
# Etapa 1: Build da aplicação React
FROM node:22 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build  # Gera a pasta "build"

# Etapa 2: Imagem final de produção com Nginx
FROM nginx:alpine

# Copia o build para o diretório padrão do Nginx
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]