name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend

    # Commenting out the test steps for now
    # - name: Run backend tests
    #   run: npm test --berbose
    #   working-directory: ./backend

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend

    # Commenting out the test steps for now
    # - name: Run frontend tests
    #   run: npm test --verbose
    #   working-directory: ./frontend

    - name: Build Docker images
      run: docker-compose -f docker-compose.prod.yml build --verbose

    - name: Push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker-compose -f docker-compose.prod.yml push
